modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="cornucopia"
version="0.1-snapshot"
displayName="Cornucopia"
updateJSONURL="http://myurl.me/"
displayURL="http://grallarius.net/"
logoFile="examplemod.png"
authors="gbromios, Enzer, Syndlig"
description='''
Farming and cooking module of the Sundered SMP mod suite.'''